version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    schedule:
      interval: "daily"
    dependencies:
      - package-name: "requests"
        version-scheme: "pessimistic"
        version: "^2.24.0"
