version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
    - package-ecosystem: "pip"
    schedule:
      interval: "daily"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    file-glob: "requirements.txt"
    version-scheme: "pypi-latest"
