name: Create Release

on:
  pull_request:
    types: [closed]

env:
  RELEASE_TAG: v0.3

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check if pull request was merged
      id: check-if-merged
      run: |
        if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
          echo "::set-output name=matches::true"
        else
          echo "::set-output name=matches::false"
        fi

    - name: Get latest release
      id: latest-release
      run: |
        latest_release=$(git describe --tags --abbrev=0)
        echo "::set-output name=latest_release::$latest_release"

    - name: Increment release version
      id: increment-version
      run: |
        version_number=$(echo ${{ steps.latest_release.outputs.latest_release }} | sed "s/$RELEASE_TAG.//")
        NEW_TAG="$RELEASE_TAG.$((version_number + 1))"
        echo "::set-env name=NEW_TAG::$NEW_TAG"

    - name: Create release
      if: steps.check-if-merged.outputs.matches == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEW_TAG }}
        release_name: Release ${{ env.NEW_TAG }}
        draft: false
        prerelease: false
