name: Create Release

on:
  pull_request:
    types: [closed, opened]

env:
  RELEASE_TAG: v0.3

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check if pull request was merged
      id: check-if-merged
      run: |
        if [ "${{ github.event.pull_request.merged }}" = true ]; then
          echo "::set-env name=PULL_REQUEST_MERGED::true"
        else
          echo "::set-env name=PULL_REQUEST_MERGED::false"
        fi

    - name: Get latest release
      id: latest-release
      uses: actions/bin/sh@v1
      with:
        args: |
          latest=$(git describe --abbrev=0 --tags)
          echo "::set-env name=LATEST_RELEASE::$latest"

    - name: Increment release version
      id: increment-version
      run: |
        NEW_TAG=$(echo $LATEST_RELEASE | sed "s/$RELEASE_TAG.*/$RELEASE_TAG.$(($(echo $LATEST_RELEASE | sed "s/.*$RELEASE_TAG.//") + 1))/")
        echo "::set-env name=NEW_TAG::$NEW_TAG"

    - name: Create release
      if: env.PULL_REQUEST_MERGED == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEW_TAG }}
        release_name: Release ${{ env.NEW_TAG }}
        draft: false
        prerelease: false
